# Generated by Django 5.0 on 2024-09-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='branch',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='events',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='year',
        ),
    ]
